### ISSUE TITLE
Possible to use this lib for non route transitions?

### ISSUE THREAD

**Issue by rohan-buchner** [PedroBern/react-tiger-transition#1]
Firstly, thank you for this really amazing pice of code, it's been really easy to learn and for someone like me whose deathly novice with animations, kind of nice to learn how to use some of them.

I am stuck however, in wanting to add an animation similair to this on a list on one of my pages.
[Codepen](https://codepen.io/cheryllaird/pen/zBvGmpw)

I have a cart thats managed in redux, and each list item is wrapped in a CSSTransition (similair to the link I shared, except i've wrapped my components in 

```
<CSSTransition
      mountOnEnter
      unmountOnExit
      in={quantity > 0}
      timeout={800}
      classNames="slide-bottom"
    >
    <Grid>{item.name}</Grid>
</CSSTransition>
```

My idea was that on reducing an items quantity to 0, it must slide out and then be removed from the DOM. 

I think my one potential problem is that I'm removing the item from the redux store collection, thus not giving the animation time to complete... but I'm unsure if thats the cause, or if I'm potentially trying to use tiger transitions for something not suited for it.

Any help or advice would be greatly appreciated.

**Comment by rohan-buchner** [comment]
So I managed to get it kind of working...

In my click handler that removes the item from the app store.
```
 // copy the store item value into a local state & use that to determine if we're at 0
  const [cartCount, setCartCount] = useState(quantity);

// delay the update of the global store by the same duration as the transition timeout
<RemoveItemClick
        value={cartCount}
        onChange={(newValue, direction) => {
          setCartCount(newValue);
          setTimeout(() => {
            onCountChange(direction);
           }, animationDelay);
       }}
 />
```

Just asking a pro :P? does this seem normal when working with redux & animations / collections?

**Comment by PedroBern** [comment]
Hi @rohan-buchner, your link to Codepen is broken.

> I think my one potential problem is that I'm removing the item from the redux store collection, thus not giving the animation time to complete... but I'm unsure if thats the cause, 

Please make a demo on [codesandbox](https://codesandbox.io/).

> or if I'm potentially trying to use tiger transitions for something not suited for it.

On the provided code you are not using `react-tiger-transition`, you are using only [react-transition-group](https://reactcommunity.org/react-transition-group/).

It's more suited for whole page transitions, but if you tweak the css you could use the animations as you want, like on [this example](https://pedrobern.github.io/react-tiger-transition/examples/material-tabs).

Although there are easier ways, as said before, it's more suited for whole page transitions, it's easier to build your own transitions without this module for simple cases, using just react-transition-group is the recommend approach.
