### ISSUE TITLE
Tiger transitions persisting across non-tiger routes

### ISSUE THREAD

**Issue by duoi** [PedroBern/react-tiger-transition#17]
Hello,

Let's say I have four pages. The first page has two tabs, clicking on the second tab would do a `history.push(url)` and take you to the third page. Clicking a link in the third page would set the tiger transition with `glide-top`. Only the third page has the transition.

Now, **any** page transition has the `glide-top` tiger transition, even if they do not have any transitions set. This means that even the tabs on the first page doing a `history.push` also perform the same transitions.

Is this intentional behaviour? If so, how can I disable it?

Thank you

**Comment by PedroBern** [comment]
You can set `globalTransitionProps ` in the `Navigation` to something like

```js
{
   classnames: 'no-transition'
}
```

See if it works
