### ISSUE TITLE
Link history to trigger transition

### ISSUE THREAD

**Issue by JeremyColton** [PedroBern/react-tiger-transition#19]
I have a link that triggers a transition when the user clicks it: 
`<Link to='/menu' transition='glideOut-right' className={classes.backLink}>   <ArrowBackIcon /></Link>`

I want to manually trigger this. I thought of using this method:
`import { withRouter } from "react-router-dom";
props.history.push("/menu");`

The history method does not let me specify the transition type. It does trigger the page to transition when called, but the 'glideOut-right' type is not used and the screen flickers once the transition has ended.

Is there a preferred way to programmatically trigger my link?

**Comment by PedroBern** [comment]
Hi @JeremyColton currently there isn't, but I'm open for a PR :)
