### ISSUE TITLE
Support Legacy React 15?

### ISSUE THREAD

**Issue by MovingGifts** [PedroBern/react-tiger-transition#44]
Hello,

Our app is stuck on an older version of React, 15.6.2 to be exact. At this point we can't upgrade the React version since a lot of things will break that were built on the older version and the respective dependency packages.

Any idea if there is way to use the react-tiger-transition with that react version?

These are the exact versions:
![image](https://user-images.githubusercontent.com/1202909/128958297-d6ea687e-3c80-40c7-90fd-9981609b00cf.png)

We tried to downgrade react-tiger-transition's codepen to the above versions and got the following error:
![image](https://user-images.githubusercontent.com/1202909/128958622-55d2ee40-0585-48c5-95a0-6f7a2175cdda.png)

But that's because these versions are the latest and won't play nicely with the legacy ones above:
![image](https://user-images.githubusercontent.com/1202909/128958703-946e6f60-57d6-4ad4-8148-8e2a7e8bce16.png)

Any idea if there are specific versions that would work with the react version above? We'd really love to improve our UX with some transitions, so we're really hoping there would be a way.

**Comment by PedroBern** [comment]
Hi @MovingGifts there isn't.

**Comment by MovingGifts** [comment]
Okay, thanks for getting back @PedroBern 👍
