### ISSUE TITLE
Could not find a declaration file for module 'react-tiger-transition'. 

### ISSUE THREAD

**Issue by davidkutas** [PedroBern/react-tiger-transition#6]
When I'm importing the `react-tiger-transition` I get a comment from VS code:

`Could not find a declaration file for module 'react-tiger-transition'. '/Users/.../.../.../.../node_modules/react-tiger-transition/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-tiger-transition` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-tiger-transition';`ts(7016)`

What does this mean? Is this an error?

**Comment by PedroBern** [comment]
It's not an error. It means that there is no declaration module for this package: it doesn't provide any typings.

[here is a question/answer](https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam) on StackOverflow that explains.
